# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#   - board: nice_nano
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  # ---------------------------------------------------------
  # Dongle (Central)
  # ---------------------------------------------------------
  - board: seeeduino_xiao_ble
    # Make sure the 'sofle_dongle' folder exists in your shields directory!
    shield: sofle_dongle prospector_adapter

  # ---------------------------------------------------------
  # Left Peripheral
  # ---------------------------------------------------------
  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter nice_view_gem
    # This forces the left half (normally central) to be a peripheral
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # ---------------------------------------------------------
  # Right Peripheral
  # ---------------------------------------------------------
  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter nice_view_gem
    # This ensures the right half stays a peripheral
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    
  # ---------------------------------------------------------
  # Settings Reset (Optional but recommended to keep handy)
  # ---------------------------------------------------------
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
